### ISSUE TITLE
Set description and website for this repo

### ISSUE THREAD

**Issue by nolleto** [fhelwanger/bayesjs-editor#14]
Hey @fhelwanger ,

I think would be great if you set a **Description** and **Website** for this repository, something like:
Description - An simple editor for Bayesian Networks
Website - http://fhelwanger.github.io/bayesjs-editor/

![Screen Shot 2019-04-15 at 10 40 09 AM](https://user-images.githubusercontent.com/2437673/56137762-e636c800-5f6b-11e9-9a5f-fbc73bac1d2b.png)

**Comment by fhelwanger** [comment]
Done 🤙
